using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class UnitSkillEffects
{
    public bool absorbDamage;
    public bool reduceDefense;
    public bool reduceAttack;
    public bool kill;
    public bool increaseAccuracy;
    public bool increaseDebuffs;
    public bool randomDebuff;
    public bool invisible;
    public bool randomDamage;
    public bool swapPosition;
    public bool knockBack;
    public bool nullDamage;
    public bool mpRestore;
    public bool attackBoost;
    public bool defenseBoost;
    public bool magicDefenseBoost;
    public bool hitReduction;
    public bool critIncrease;
    public bool damageReduction;
    public bool extraHit;
    public bool holyDamage;
    public bool fireDamage;
    public bool healing;
    public bool extraTurn;
    public bool revive;
    public bool magicBoost;
    public bool willBoost;
    public bool skillUseRestore;
    public bool poison;
    public bool sleep;
    public bool shaken;
    public bool stun;
    public bool root;
    public bool confuse;
    public bool berserk;
    public bool vampire;
    public bool selfDamage;
    public bool counter;
    public bool hitrateReduce;
    public bool dodge;
    public bool stealMoney;
    public bool stealItem;
    public bool darkDamage;
    public bool waterDamage;
    public bool earthDamage;
    public bool natureDamage;
    public bool metalDamage;
    public bool trueDamage;
    public bool overRun;
    public bool movementDown;
    public bool movementIncrease;
    public bool statusHeal;

    public UnitSkillEffects()
    {
        reduceAttack = false;
        magicBoost = false;
        absorbDamage = false;
        reduceDefense = false;
        kill = false;
        increaseAccuracy = false;
        increaseDebuffs = false;
        randomDebuff = false;
        invisible = false;
        critIncrease = false;
        shaken = false;
        randomDamage = false;
        root = false;
        confuse = false;
        stun = false;
        swapPosition = false;
        statusHeal = false;
        counter = false;
        mpRestore = false;
        nullDamage = false;
        selfDamage = false;
        hitReduction = false;
        knockBack = false;
        attackBoost = false;
        defenseBoost = false;
        skillUseRestore = false;
        willBoost = false;
        damageReduction = false;
        extraHit = false;
        extraTurn = false;
        poison = false;
        sleep = false;
        berserk = false;
        vampire = false;
        holyDamage = false;
        darkDamage = false;
        fireDamage = false;
        waterDamage = false;
        earthDamage = false;
        natureDamage = false;
        metalDamage = false;
        trueDamage = false;
        healing = false;
        revive = false;
        hitrateReduce = false;
        dodge = false;
        stealItem = false;
        stealMoney = false;
        overRun = false;
        movementDown = false;
        movementIncrease = false;
    }
}
